src/Entity/Ammende.php
<?php

namespace App\Entity;

use App\Repository\AmmendeRepository;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AmmendeRepository::class)
 */
class Ammende
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $prix;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDateCreation(): ?DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }
}

src/Form/AmmendeType.php
<?php

namespace App\Form;

use App\Entity\Ammende;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AmmendeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('prix')  
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Ammende::class,
        ]);
    }
}

src/Controller/AmmendeController.php
<?php

namespace App\Controller;

use App\Entity\Ammende;
use App\Form\AmmendeType;
use App\Repository\AmmendeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/ammende')]
class AmmendeController extends AbstractController
{
    #[Route('/', name: 'app_ammende_index', methods: ['GET'])]
    public function index(AmmendeRepository $ammendeRepository): Response
    {
        return $this->render('ammende/index.html.twig', [
            'ammendes' => $ammendeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_ammende_new', methods: ['GET', 'POST'])]
    public function new(Request $request, AmmendeRepository $ammendeRepository): Response
    {
        $ammende = new Ammende();
        $form = $this->createForm(AmmendeType::class, $ammende);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $ammende->setDateCreation(date_create(date('Y-m-d H:i:s')));
            $ammendeRepository->add($ammende, true);

            return $this->redirectToRoute('app_ammende_new', [], Response::HTTP_SEE_OTHER);
        }
        return $this->renderForm('ammende/new.html.twig', [
            'ammende' => $ammende,
            'form' => $form,
        ]);
    }
 
}

templates/ammende/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/ammende/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ammende index{% endblock %}

{% block body %}
    <h1>Ammende index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Prix</th>
                <th>Date_creation</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for ammende in ammendes %}
            <tr>
                <td>{{ ammende.id }}</td>
                <td>{{ ammende.prix }}</td>
                <td>{{ ammende.dateCreation ? ammende.dateCreation|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_ammende_new') }}">Create new</a>
{% endblock %}

templates/ammende/new.html.twig
{% extends 'adminTemplate.html.twig' %}

{% form_theme form 'form_div_layout.html.twig' %}

{% block pageName %} 
Ammende
{% endblock %}

{% block body %}
<section class="content">
      <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <div class="card card-primary">
                <div class="card-header">
                    <h1 class="card-title">Ajouter une nouvelle Ammende</h1>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                {{ form_start(form) }}
                    <div class="card-body">
                    <div class="form-group">
                        {{ form_label(form.prix) }}
                        {{form_widget(form.prix, { 'attr': {'class': 'form-control'} }) }}

                    </div>
                   
                    <!-- /.card-body -->
                    <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Ajouter</button>
                    </div>
                {{ form_end(form) }}
                </div>
            </div>
            <!-- /.card -->
        </div>
</section>
{% endblock %}